In [8]:
import numpy as np
import plotly.graph_objects as go

In [18]:
carts = np.load("cartesians_history.npy.npz")
x = carts['x']
y = carts['y']
z = carts['z']

In [19]:
fig = go.Figure(go.Scatter3d(x = [], y = [], z = [],
                             mode = "markers",
                             marker = dict(color = "red", size = 5)
                             ))
    
# Frames
frames = [go.Frame(data = [go.Scatter3d(x = x[k, :],
                                        y = y[k, :],
                                        z = z[k, :]
                                        )
                          ],
                   traces = [0],
                   name = f'frame{k}'      
                  ) for k in range(len(x)-1)
          ]

fig.update(frames = frames)

def frame_args(duration):
    return {
            "frame": {"duration": duration},
            "mode": "immediate",
            "fromcurrent": True,
            "transition": {"duration": duration, "easing": "linear"},
            }


sliders = [
    {"pad": {"b": 10, "t": 60},
     "len": 0.9,
     "x": 0.1,
     "y": 0,
     
     "steps": [
                 {"args": [[f.name], frame_args(0)],
                  "label": str(k),
                  "method": "animate",
                  } for k, f in enumerate(fig.frames)
              ]
     }
        ]

fig.update_layout(

    updatemenus = [{"buttons":[
                    {
                        "args": [None, frame_args(50)],
                        "label": "Play", 
                        "method": "animate",
                    },
                    {
                        "args": [[None], frame_args(0)],
                        "label": "Pause", 
                        "method": "animate",
                  }],
                    
                "direction": "left",
                "pad": {"r": 10, "t": 70},
                "type": "buttons",
                "x": 0.1,
                "y": 0,
            }
         ],
         height = 600,
         width = 600,
         sliders = sliders)

fig.update_layout(scene = dict(xaxis = dict(range = [x.min() - 1, x.max() + 2], autorange = False),
                               yaxis = dict(range = [y.min() - 1, y.max() + 2], autorange = False),
                               zaxis = dict(range = [z.min() - 1, z.max() + 2], autorange = False)))

fig.update_layout(sliders = sliders)
fig.show()

In [4]:
carts = np.load("cartesians_actual_coordwise.npy.npz")
x = carts['x'][:10]
y = carts['y'][:10]
z = carts['z'][:10]
x.shape

(10, 180)

In [5]:
fig = go.Figure(go.Scatter3d(x = [], y = [], z = [],
                             mode="markers",
                             marker=dict(color="red", size=5)
                             ))
    
# Frames
frames = [go.Frame(data = [go.Scatter3d(x = x[k, :],
                                        y = y[k, :],
                                        z = z[k, :]
                                        )
                          ],
                   traces = [0],
                   name = f'frame{k}'      
                  ) for k in range(len(x)-1)
          ]

fig.update(frames = frames)

def frame_args(duration):
    return {
            "frame": {"duration": duration},
            "mode": "immediate",
            "fromcurrent": True,
            "transition": {"duration": duration, "easing": "linear"},
            }


sliders = [
    {"pad": {"b": 10, "t": 60},
     "len": 0.9,
     "x": 0.1,
     "y": 0,
     
     "steps": [
                 {"args": [[f.name], frame_args(0)],
                  "label": str(k),
                  "method": "animate",
                  } for k, f in enumerate(fig.frames)
              ]
     }
        ]

fig.update_layout(

    updatemenus = [{"buttons":[
                    {
                        "args": [None, frame_args(50)],
                        "label": "Play", 
                        "method": "animate",
                    },
                    {
                        "args": [[None], frame_args(0)],
                        "label": "Pause", 
                        "method": "animate",
                  }],
                    
                "direction": "left",
                "pad": {"r": 10, "t": 70},
                "type": "buttons",
                "x": 0.1,
                "y": 0,
            }
         ],
         height = 600,
         width = 600,
         sliders = sliders)

fig.update_layout(scene = dict(xaxis = dict(range = [x.min() - 1, x.max() + 2], autorange = False),
                               yaxis = dict(range = [y.min() - 1, y.max() + 2], autorange = False),
                               zaxis = dict(range = [z.min() - 1, z.max() + 2], autorange = False)))

fig.update_layout(sliders = sliders)
fig.show()

In [35]:
forces_actual = np.load("forces_actual.npy.npz")['forces']
forces_history = np.load("forces_history.npy.npz")['forces']

In [31]:
forces_actual.mean(axis = 0)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00

In [36]:
forces_history.mean(axis=0)

array([[ 1.08990088e+04, -2.92239716e+02, -2.54669873e+03],
       [ 9.25204883e+03,  2.38243970e+03,  1.11594209e+04],
       [-2.99079297e+03, -5.60120361e+02, -1.59233506e+04],
       [-1.03269678e+03, -7.46132080e+03, -1.07939648e+04],
       [-1.66830969e+03,  8.65860059e+03, -2.78753770e+04],
       [-5.38002930e+03,  8.25606689e+02, -1.98563418e+04],
       [-1.23968057e+04, -2.75559052e+02, -1.02089233e+03],
       [ 9.43844531e+03, -1.70003528e+03,  5.55135010e+03],
       [ 5.25433740e+03,  5.57757715e+03,  1.04351914e+04],
       [ 2.40549561e+02,  1.09305361e+04,  2.31526055e+04],
       [ 1.15327625e+03,  2.40781876e+02,  1.55613506e+04],
       [ 8.45834961e+03, -8.28389551e+03, -1.89370820e+04],
       [ 5.71506104e+03,  2.14588647e+03,  1.49131025e+04],
       [ 8.33822559e+03,  1.48320764e+03,  2.15453066e+04],
       [ 1.64921558e+03,  9.22322693e+02,  1.31262686e+04],
       [ 7.52472046e+02, -7.45838623e+02,  7.81489404e+03],
       [-7.17756104e+03,  2.08744653e+03

In [10]:
velocities = np.load("velocities_actual.npy.npz")['velocities']

In [11]:
velocities.mean(axis = 0)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00