In [53]:
import numpy as np
import plotly.graph_objects as go

In [54]:
carts = np.load("cartesians_history.npy.npz")
x = carts['x']
y = carts['y']
z = carts['z']

In [55]:
fig = go.Figure(go.Scatter3d(x = [], y = [], z = [],
                             mode = "markers",
                             marker = dict(color = "red", size = 5)
                             ))
    
# Frames
frames = [go.Frame(data = [go.Scatter3d(x = x[k, :],
                                        y = y[k, :],
                                        z = z[k, :]
                                        )
                          ],
                   traces = [0],
                   name = f'frame{k}'      
                  ) for k in range(len(x)-1)
          ]

fig.update(frames = frames)

def frame_args(duration):
    return {
            "frame": {"duration": duration},
            "mode": "immediate",
            "fromcurrent": True,
            "transition": {"duration": duration, "easing": "linear"},
            }


sliders = [
    {"pad": {"b": 10, "t": 60},
     "len": 0.9,
     "x": 0.1,
     "y": 0,
     
     "steps": [
                 {"args": [[f.name], frame_args(0)],
                  "label": str(k),
                  "method": "animate",
                  } for k, f in enumerate(fig.frames)
              ]
     }
        ]

fig.update_layout(

    updatemenus = [{"buttons":[
                    {
                        "args": [None, frame_args(50)],
                        "label": "Play", 
                        "method": "animate",
                    },
                    {
                        "args": [[None], frame_args(0)],
                        "label": "Pause", 
                        "method": "animate",
                  }],
                    
                "direction": "left",
                "pad": {"r": 10, "t": 70},
                "type": "buttons",
                "x": 0.1,
                "y": 0,
            }
         ],
         height = 600,
         width = 600,
         sliders = sliders)

fig.update_layout(scene = dict(xaxis = dict(range = [x.min() - 1, x.max() + 2], autorange = False),
                               yaxis = dict(range = [y.min() - 1, y.max() + 2], autorange = False),
                               zaxis = dict(range = [z.min() - 1, z.max() + 2], autorange = False)))

fig.update_layout(sliders = sliders)
fig.show()

In [56]:
carts = np.load("cartesians_actual_coordwise.npy.npz")
x = carts['x'][:100]
y = carts['y'][:100]
z = carts['z'][:100]

In [57]:
fig = go.Figure(go.Scatter3d(x = [], y = [], z = [],
                             mode="markers",
                             marker=dict(color="red", size=5)
                             ))
    
# Frames
frames = [go.Frame(data = [go.Scatter3d(x = x[k, :],
                                        y = y[k, :],
                                        z = z[k, :]
                                        )
                          ],
                   traces = [0],
                   name = f'frame{k}'      
                  ) for k in range(len(x)-1)
          ]

fig.update(frames = frames)

def frame_args(duration):
    return {
            "frame": {"duration": duration},
            "mode": "immediate",
            "fromcurrent": True,
            "transition": {"duration": duration, "easing": "linear"},
            }


sliders = [
    {"pad": {"b": 10, "t": 60},
     "len": 0.9,
     "x": 0.1,
     "y": 0,
     
     "steps": [
                 {"args": [[f.name], frame_args(0)],
                  "label": str(k),
                  "method": "animate",
                  } for k, f in enumerate(fig.frames)
              ]
     }
        ]

fig.update_layout(

    updatemenus = [{"buttons":[
                    {
                        "args": [None, frame_args(50)],
                        "label": "Play", 
                        "method": "animate",
                    },
                    {
                        "args": [[None], frame_args(0)],
                        "label": "Pause", 
                        "method": "animate",
                  }],
                    
                "direction": "left",
                "pad": {"r": 10, "t": 70},
                "type": "buttons",
                "x": 0.1,
                "y": 0,
            }
         ],
         height = 600,
         width = 600,
         sliders = sliders)

fig.update_layout(scene = dict(xaxis = dict(range = [x.min() - 1, x.max() + 2], autorange = False),
                               yaxis = dict(range = [y.min() - 1, y.max() + 2], autorange = False),
                               zaxis = dict(range = [z.min() - 1, z.max() + 2], autorange = False)))

fig.update_layout(sliders = sliders)
fig.show()

In [58]:
forces_actual = np.load("forces_actual.npy.npz")['forces']
forces_history = np.load("forces_history.npy.npz")['forces']

In [59]:
forces_actual.mean(axis = 0)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00

In [60]:
forces_history.mean(axis=0)

array([[ 5.09732664e-01,  1.42302528e-01,  3.56229573e-01],
       [ 3.04675221e-01,  4.81392175e-01,  5.37200153e-01],
       [ 3.95434676e-03,  5.89517117e-01,  9.01991129e-01],
       [ 2.22827657e-03,  5.49204648e-01,  1.05147433e+00],
       [-1.03903800e-01,  6.72570765e-01,  7.21923649e-01],
       [-4.23594862e-01,  6.77375436e-01,  8.02040160e-01],
       [ 7.57670343e-01, -1.86606407e-01,  4.83637989e-01],
       [ 3.69774073e-01, -5.80000393e-02,  7.28776753e-01],
       [ 2.48353649e-03,  1.48555860e-01,  1.36603498e+00],
       [ 2.57170270e-03,  1.70245633e-01,  9.47334230e-01],
       [-2.06442460e-01,  2.80971020e-01,  1.09969330e+00],
       [-5.04983127e-01,  4.25878644e-01,  9.94967818e-01],
       [ 6.60458028e-01, -4.29259777e-01,  5.71900010e-01],
       [ 3.58103067e-01, -3.05096179e-01,  7.43546069e-01],
       [ 7.03384809e-04, -1.65603980e-02,  9.84242678e-01],
       [ 2.49617820e-04, -1.20543828e-02,  1.04344201e+00],
       [-2.71883190e-01,  1.21325560e-01

In [61]:
velocities = np.load("velocities_actual.npy.npz")['velocities']

In [62]:
velocities.mean(axis = 0)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00